language: python
python:
  - "2.7"
  - "3.5"

install: "pip install -r requirements.txt"
script: python manage.py test

# build all branches except testing branches
branches:
  except:
   - /^testing.*/
